import { writeFileSync } from 'fs';
import * as YAML from 'yaml';
import { JsonPatch } from './json-patch';

/**
 * Options for `YamlFile`
 */
export interface YamlFileOptions {
  /**
   * The object that will be serialized. You can modify the object's contents
   * before synthesis.
   *
   * @default {} an empty object
   */
  readonly obj?: any;
}

/**
 * Represents a Yaml File.
 */
export class YamlFile {
  /**
   * The path to the file that the object will be written to.
   */
  private readonly filePath: string;

  /**
   * The output object. This object can be mutated until the project is synthesized.
   */
  private obj: object;

  /**
   * Patches to be applied to `obj` after the resolver is called.
   */
  private readonly patchOperations: JsonPatch[];

  /**
   * A comment to be added to the top of the YAML file.
   *
   * Can be multiline. All non-empty line are pefixed with '# '. Empty lines are kept, but not commented.
   *
   * For example:
   * ```ts
   * pipeline.workflowFile.commentAtTop =
   * `AUTOGENERATED FILE, DO NOT EDIT!
   * See ReadMe.md
   * `;
   * ```
   *
   * Results in YAML:
   * ```yaml
   * # AUTOGENERATED FILE, DO NOT EDIT!
   * # See ReadMe.md
   *
   * name: deploy
   * ...
   * ```
   */
  public commentAtTop?: string;

  /**
   * A comment to be added to the bottom of the YAML file.
   *
   * Can be multiline. All non-empty line are pefixed with '# '. Empty lines are kept, but not commented.
   *
   * For example:
   * ```ts
   * pipeline.workflowFile.commentAtBottom = `Included in this deployment:\n\n${ENVIRONMENTS.map((e) => ` - ${e.name}`).join('')}`;
   * ```
   *
   * Results in YAML:
   * ```yaml
   * name: deploy
   * on:
   *   push:
   * < remaining pipeline yaml contents here >
   *
   * # Included in this deployment:
   *
   * #  - Dev1
   * #  - Dev2
   * #  - UAT1
   * ```
   */
  public commentAtBottom?: string;

  constructor(filePath: string, options: YamlFileOptions = {}) {
    this.filePath = filePath;
    this.obj = options.obj ?? {};
    this.patchOperations = [];
  }

  /**
   * Update the output object.
   */
  public update(obj: any) {
    this.obj = obj;
  }

  /**
   * Applies an RFC 6902 JSON-patch to the synthesized object file.
   * See https://datatracker.ietf.org/doc/html/rfc6902 for more information.
   *
   * For example, with the following yaml file
   * ```yaml
   * name: deploy
   * on:
   *   push:
   *     branches:
   *       - main
   *   workflow_dispatch: {}
   * ...
   * ```
   *
   * modified in the following way:
   *
   * ```ts
   * pipeline.workflowFile.patch(JsonPatch.add("/on/workflow_call", "{}"));
   * pipeline.workflowFile.patch(JsonPatch.remove("/on/workflow_dispatch"));
   * ```
   *
   * would result in the following yaml file:
   *
   * ```yaml
   * name: deploy
   * on:
   *   push:
   *     branches:
   *       - main
   *   workflow_call: {}
   * ...
   * ```
   *
   * @param patches - The patch operations to apply
   */
  public patch(...patches: JsonPatch[]) {
    this.patchOperations.push(...patches);
  }

  /**
   * Returns the patched yaml file.
   */
  public toYaml(): string {
    const patched = JsonPatch.apply(this.obj, ...this.patchOperations);

    const yamlDoc = new YAML.Document(patched);
    yamlDoc.commentBefore = this.commentAtTop ?? null;
    yamlDoc.comment = this.commentAtBottom ?? null;

    return yamlDoc.toString({
      commentString: (comment) =>
        comment.split('\n').map((x) => x == '' ? '' : `# ${x}`).join('\n'),
      indent: 2,
    });
  }

  /**
   * Write the patched yaml file to the specified location.
   */
  public writeFile() {
    writeFileSync(this.filePath, this.toYaml());
  }
}
